services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "8001:6379"  # Mapeamos el puerto 6379 de Redis al puerto 8001 del host
    networks:
      - app-network

  app1:
    image: mi-app-node:2.0  # Imagen de la app
    container_name: app1
    environment:
      NODE_ENV: production
      INSTANCE_ID: app1
    ports:
      - "3001:3000"  # Mapeamos el puerto 3001 del host al puerto 3000 del contenedor
    depends_on:
      - redis  # Garantiza que Redis se levante antes que la app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge