{
 "title": "TP2 DEVOPS 2024",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Metricas app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tareas Agregadas",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tasks_added_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Tareas Modificadas",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tasks_state_changes_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Tareas Eliminadas",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tasks_deleted_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Tareas agregadas / minuto",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "floor(increase(tasks_added_total[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tareas modificadas/ minuto",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "floor(increase(tasks_state_changes_total[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tareas eliminadas/ minuto",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "floor(increase(tasks_deleted_total[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Productivo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "%CPU APP1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"app1\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory APP1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_memory_usage_bytes{name=\"app1\"}[1m])) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "%CPU APP2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"app2\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory APP2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_memory_usage_bytes{name=\"app2\"}[1m])) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "%CPU redis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"server-redis\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory redis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_memory_usage_bytes{name=\"server-redis\"}[1m])) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "%CPU cadvisor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"cadvisor\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory cadvisor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_memory_usage_bytes{name=\"cadvisor\"}[1m])) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "%CPU over time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"app1\"}[1m]) * 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"app2\"}[1m]) * 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"server-redis\"}[1m]) * 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"cadvisor\"}[1m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "%CPU over time",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"app1\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"app2\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"server-redis\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"cadvisor\"}[1m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "%CPU over time",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"app1\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"app2\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"server-redis\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"cadvisor\"}[1m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "%CPU over time",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"app1\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"app2\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"server-redis\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"cadvisor\"}[1m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}